import {
	COLOR_ACTION_600,
	COLOR_ALERT_100_OPAQUE,
	COLOR_ALERT_300, COLOR_AQUA_BLUE,
	COLOR_DARK_SPACE,
	COLOR_ECONOM_100,
	COLOR_ECONOM_300,
	COLOR_ECONOM_400,
	COLOR_INFO_100_OPAQUE,
	COLOR_INFO_500,
	COLOR_NEGATIVE_300,
	COLOR_NEGATIVE_400,
	COLOR_NEGATIVE_500,
	COLOR_NEUTRAL_600,
	COLOR_OZON_BLUE,
	COLOR_OZON_MAGENTA,
	COLOR_PRO_400,
	COLOR_PRO_600,
	COLOR_WREATH_GREEN,
	COLOR_YELLOW_STAR,
} from '@/constants/colors'

export {
	COLOR_ACTION_400 as PIE_CHART_COLOR_INFO,
	COLOR_ALERT_600 as PIE_CHART_COLOR_ERROR,
	COLOR_NEUTRAL_500 as PIE_CHART_COLOR_DEBUG,
	COLOR_WARNING_300 as PIE_CHART_COLOR_WARNING,
	COLOR_SUCCESS_400 as PIE_CHART_COLOR_SUCCESS,
	COLOR_NEUTRAL_400 as PIE_CHART_COLOR_NEUTRAL,
	COLOR_PRO_500 as PIE_CHART_COLOR_OTHER,
} from '@/constants/colors'

export const RANDOM_OZI_COLORS = [
	COLOR_NEUTRAL_600,

	COLOR_NEGATIVE_500,
	COLOR_NEGATIVE_400,
	COLOR_NEGATIVE_300,

	COLOR_ALERT_300,
	COLOR_ALERT_100_OPAQUE,

	COLOR_INFO_500,
	COLOR_INFO_100_OPAQUE,

	COLOR_ACTION_600,

	COLOR_PRO_600,
	COLOR_PRO_400,

	COLOR_ECONOM_400,
	COLOR_ECONOM_300,
	COLOR_ECONOM_100,

	COLOR_OZON_BLUE,
	COLOR_OZON_MAGENTA,
	COLOR_WREATH_GREEN,
	COLOR_YELLOW_STAR,
	COLOR_AQUA_BLUE,
	COLOR_DARK_SPACE,
]
